apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-monitor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-monitor
  template:
    metadata:
      labels:
        app: k8s-monitor
    spec:
      containers:
      - name: k8s-monitor
        image: foun1224/k8s-monitor:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"