apiVersion: v1
kind: Service
metadata:
  name: k8s-monitor-service
  namespace: default
spec:
  selector:
    app: k8s-monitor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP